version: '3'
services:

  backend:
    build:
      context: ./books-backend
      dockerfile: Dockerfile  
    volumes:
      - /app/node_modules
      - ./service/config:/app/config
      - ./service/src:/app/src
      - ./service/test:/app/test
    ports:
      - "3001:3001"

  database:
    image: postgres:12.1
    ports:
      - "5432:5432"
    env_file:
      - .env

  frontend:
    build:
      context: ./books-frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./books-frontend:/app
    ports:
      - "8080:3000"